### ISSUE TITLE
Document the version of solaredge-modbus required

### ISSUE THREAD

**Issue by dickon** [fredlcore/SolarEdge_Predictive_Charging#1]
Background: I found this project while researching SolarEdge and want to adapt it for a new PV install, and so I studied through the code to be confident how much I could do via modes.

Reading through the code, I see the code writes to register `storage_control_mode`. However, I don't see that symbol in 0.7.0 of solaredge-modbus so I don't see how that would work.

Probably best to have a requirements.txt which specifies the package requirements including `solaredege-modbus`.

**Comment by fredlcore** [comment]
The current release package of solaredge-modbus does not contain this register, I had asked for its implementation, but so far this hasn't happened yet, see here:
https://github.com/nmakel/solaredge_modbus/issues/36
In the end, I modified the code myself to make it work.

**Comment by fredlcore** [comment]
I added a version of nmakel's library with my changes here: https://github.com/fredlcore/SolarEdge_Predictive_Charging/issues/3#issuecomment-1945862563
So hopefully with this one, it will work.
