### ISSUE TITLE
SolarEdge Energy Manager Modes

### ISSUE THREAD

**Issue by S-Woodford** [fredlcore/SolarEdge_Predictive_Charging#2]
Hi

Firstly, thank-you for the excellent code you wrote, and for sharing.

I am interested in building on your code to optimise battery charging based on cheap overnight charging and the Solcast, i.e. to only charge the battery during cheaper overnight periods to a minimum level required to get through the following day.  I have much of the logic mapped and have writted a large chunk of the code based on what you have done, but I don't really understand the commands to change the inverter mode, e.g.
inverter.write("storage_control_mode", 4)
inverter.write("storage_default_mode", 7)
mode = "Maximize export"
inverter.write("rc_cmd_mode", 4)

Specifically, I don't know what the first two are for ("storage_control_mode" and "storage_default_mode"), and the labels are not exactly the same as those in the Application Note – Battery Profile Programming on the Monitoring Platform (https://knowledge-center.solaredge.com/sites/kc/files/storedge_charge_discharge_profile_programming.pdf).  Also, what do the "rc_cmd_mode" numbers refer to?  If they are the position in the table, have they changed since you wrote your code? So, I guess my big question is: are you able to provide an explanation of how these elements work, please?  I would be very grateful for any help & advice, as I haven't written any 'proper code' in over 25 years and have never programmed in Python - it has been a very steep learning curve!

Many thanks in advance

Spence

**Comment by fredlcore** [comment]
Hi Spence, 

glad to hear my little script is helpful. 
The terms more or less refer to this document:
https://www.photovoltaikforum.com/core/attachment/88445-power-control-open-protocol-for-solaredge-inverters-pdf/
Storage Control Mode is a setting that defines how the inverter behaves generally: maximize self consumption, time of use profiles etc. - or "remote control" which has the value 4. Only in this mode you can then control the behaviour of the inverter with the Remote Control Command Mode. These modes are listed in the linked document on page 17 at the bottom. With Storage Default Mode, you can set a default mode to which the inverter falls back to after the time in seconds defined in Remote Control Command Timeout.
Therefore it is necessary to set anew the Remote Control Command Mode at least once before this timeout expires.

Hope that helps!

**Comment by S-Woodford** [comment]
Very many thanks for your reply - much appreciated!I have seen the document before, but I will read it again in the context of your input below. At the moment, I can’t seem to write to the inverter, even trying to set the Remote Control Command Mode to ‘on’. I’ll have to try again tomorrow…Thanks againSpence

**Comment by fredlcore** [comment]
You have to set Storage Remote Control (0xE004) to value 4 first before you can change the Remote Control Command Mode.
Furthermore, the manual mentions the following conditions that have to be met as well:
```
o enable StorEdge control, make sure the following is set:
- AdvancedPwrControlEn on address 0xF142 to 1 (enable). It is disabled (0) by default.
- ReactivePwrConfig on address 0xF104 to 4 (RRCR mode). It is set by default to 0 (Fixed CosPhi mode).
- Issue a Commit Power Control Settings command on address 0xF100 to make this setting effective.
```
I didn't have to do this as apparently StorEdge control was already activated (maybe by the installer or through the SetApp app), but it might be worth checking.

**Comment by S-Woodford** [comment]
Thanks again for your help!  Having looked at the options on the SetApp app, I’m not sure that Remote Control is an option any more.  I’ll connect to the inverter via the web interface and see whether I can make the changes via the browser app before trying the code again…

Spence

**Comment by fredlcore** [comment]
Well, I just checked that the script actually takes care of that itself, i.e. setting Storage Control Mode to 4, as you quoted above:
```
inverter.write("storage_control_mode", 4)
```
So that shouldn't be an issue actually. The other three commands mentioned before might be worth checking/adding.
Also make sure that the ModBus port is correct because the default in your inverter may not be the ModBus standard port...

**Comment by S-Woodford** [comment]
Thanks again for your help with this. I fear that some of the issues I am experiencing are due to firmware changes, but I may well be wrong… 🤷🏼‍♂️ I can access data from the inverter, so the IP & port values are ok. From the inverter data, I can see that:“storage remote control” does not appear. Bad;“advanced_power_control_enable” = 1. Good!“reactive_power_config” = 4.  Good!“commit_power_control_settings” = 0. Bad.The inverter does not give an error code when I issue the command,  “inverter.write(“commit_power_control_settings”, 1)”, but the value does not change. I wonder if this is because the Storage Remote Control is not set. I can’t see a way to change this in SetApp. Any idea how to switch on remote control directly?Thanks againSpence

**Comment by fredlcore** [comment]
Hm, maybe your version of solaredge-modbus does not include those parameters? Have you seen this #1?

**Comment by S-Woodford** [comment]
I’ve just been having a look through some of the exchanges that you linked to - it blows my mind, especially Herbi3’s init.py file. I’ll need to look into it some more, but I don’t currently understand which lines (as a minimum) I need to include in my script to enable the ability to switch Energy Manager modes between ‘charge from grid’, ‘no charge or discharge’, and ‘self-consumption’. Writing directly to the registers on the inverter appears to be required with my (latest) firmware, but I can see from your previous exchanges with nmakel that it is complicated…!SpenceSent from my iPhone - please excuse brevity or spelling errors.On 17 Mar 2023, at 13:57, fredlcore ***@***.***> wrote:﻿
Hm, maybe your version of solaredge-modbus does not include those parameters? Have you seen this #1?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/fredlcore/SolarEdge_Predictive_Charging/issues/2#issuecomment-1473884228",
"url": "https://github.com/fredlcore/SolarEdge_Predictive_Charging/issues/2#issuecomment-1473884228",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by fredlcore** [comment]
Have a look here, I added the version of nmakel's library which include my changes - although this is based on his library in a version of 2022: https://github.com/fredlcore/SolarEdge_Predictive_Charging/issues/3#issuecomment-1945862563
