### ISSUE TITLE
Changing the battery profiles

### ISSUE THREAD

**Issue by milkotodorov** [fredlcore/SolarEdge_Predictive_Charging#3]
How did you manage to change the battery profiles with `inverter.write("rc_cmd_mode", 7)`?
This is somehow not implemented in `solaredge_modbus`. Perhaps this is not working on the "SolarEdge Home Hub Inverters"?

**Comment by fredlcore** [comment]
It's not implemented yet, see #1. I added the ModBus parameters manually in the library.

**Comment by milkotodorov** [comment]
I see - thanks. Would you share how did you add them? Similar to this: https://github.com/herbi3/solaredge_modbus/blob/master/src/solaredge_modbus/__init__.py#L525-L549?

**Comment by fredlcore** [comment]
I would do that, but I don't know where MacOS stores installed python3 libraries such as solaredge_modbus. I have made these changes two years ago and told the maintainer that they were missing and he said he would look into them, so then I forgot about it. If you know where I could/should look, I could add the file to this repo.

**Comment by milkotodorov** [comment]
That would be great if you can add this here to your repo.
You can get it via `python3 -m site` or `python -m site` (if you have only Python3 installed).
If you use `pip` to install the packages you can use `pip --version` and you will see the folder where the `pip` installs the packages.

**Comment by fredlcore** [comment]
Thanks! Unfortunately, I just realized that I wrote this script (and therefore also the changes in solaredge_modbus) on my old MacBook. The backup I made of this machine was limited to my user's folder, so these changes are now lost, as I didn't transfer the library changes because in my home automation software (FHEM) I'm now accessing the SolarEdge inverter through FHEM's ModBus module.

So the only remaining information that I have is the one I posted in this issue here (including some code lines):
https://github.com/nmakel/solaredge_modbus/issues/36
If someone (you?) would manage to add the missing parameters to solaredge_modbus, maybe you could either submit a PR for the main repo or you fork it and I link to that fork in my README. I'm sorry that I cannot be of any greater help, but in the end the changes should be rather quick to make - if you know a bit of Python, I guess...

**Comment by milkotodorov** [comment]
I will. I was just curious how did you implemented it as the Endian for these registers seems to be different (Little). One solution was to add them as separate class as mentioned above. This works.

**Comment by fredlcore** [comment]
Great, looking forward to see (and add/link) your implenetation - or even better, upstream will add them!

**Comment by milkotodorov** [comment]
You can check it out here: https://github.com/milkotodorov/solaredge-battery-control
Unfortunately, it's not working flawlessly, but as a workaround. I described the issues in the [limitation section](https://github.com/milkotodorov/solaredge-battery-control#limitations). With such limitations it won't be nice to merge into `solaredge_modbus` project. I wonder how did you add them without having the issues with `storage_control_mode`, `storage_default_mode` and `storage_backup_reserved_setting`?

**Comment by fredlcore** [comment]
Sorry for the long delay in getting back to you.
I'm not really sure if I unknowingly also encountered these problems and just tried it again without realizing that it was not a network issue but something like you encountered.
I _think_ I did nothing more than writing the value like this:
https://github.com/nmakel/solaredge_modbus/issues/36#issuecomment-897395864
So just passing the data directly without any extra class involved. From what I can tell with my current, direct ModBus implementation running under FHEM, the changes take immediate effect and the problem you describe does not occur. So I wonder why it would/should occur in solar_modbus?

**Comment by fredlcore** [comment]
I actually found the files on my NAS!
I attach the complete folder structure just in case any of that is necessary, but I think I only made changes in the __init__.py file. These changes are those:
1. I removed this line:
`               return self._write_holding_register(address, self._encode_value(data, dtype))`
and replaced it with this line:
`                return self._write_holding_register(address, data)`
The reason for this is that (at that time at least) the necessary function to encode data to a register was still missing in the library, so I just passed the value directly. This worked for the registers that I was working with, not sure if it works as well for others and maybe this isn't even necessary anymore nowadays.

2. I commented out these lines:
```
#            "rrcr_state": (0xf000, 1, registerType.HOLDING, registerDataType.UINT16, int, "RRCR State", "", 3),
#            "active_power_limit": (0xf001, 1, registerType.HOLDING, registerDataType.UINT16, int, "Active Power Limit", "%", 3),
#            "cosphi": (0xf002, 2, registerType.HOLDING, registerDataType.FLOAT32, int, "CosPhi", "", 3)
```
I don't remember why. Maybe there was a maximum number of parameters?

And 3., before these commented-out lines, I added these new parameters:
```
            "storage_control_mode": (0xe004, 1, registerType.HOLDING, registerDataType.UINT16, int, "Storage Control Mode", "", 3),
            "storage_ac_charge_policy": (0xe005, 1, registerType.HOLDING, registerDataType.UINT16, int, "Storage AC Charge Policy", "", 3),
            "storage_ac_charge_limit": (0xe006, 2, registerType.HOLDING, registerDataType.FLOAT32, float, "Storage AC Charge Limit", "", 3),
            "storage_backup_reserved_setting": (0xe008, 2, registerType.HOLDING, registerDataType.FLOAT32, float, "Storage Backup Reserved Setting", "%", 3),
            "storage_default_mode": (0xe00a, 1, registerType.HOLDING, registerDataType.UINT16, int, "Storage Charge/Discharge Default Mode", "", 3),
            "rc_cmd_timeout": (0xe00b, 2, registerType.HOLDING, registerDataType.UINT32, int, "Remote Control Command Timeout", "s", 3),
            "rc_cmd_mode": (0xe00d, 1, registerType.HOLDING, registerDataType.UINT16, int, "Remote Control Command Mode", "", 3),
            "rc_charge_limit": (0xe00e, 2, registerType.HOLDING, registerDataType.FLOAT32, float, "Remote Control Command Charge Limit", "W", 3),
            "rc_discharge_limit": (0xe010, 2, registerType.HOLDING, registerDataType.FLOAT32, float, "Remote Control Command Discharge Limit", "W", 3)
```

I don't know which/if any of these changes are still necessary today, but this is the state of the library that my python script will work with.
[solaredge_modbus-master.zip](https://github.com/fredlcore/SolarEdge_Predictive_Charging/files/14295944/solaredge_modbus-master.zip)
