### ISSUE TITLE
What format are the values in?

### ISSUE THREAD

**Issue by phoenix1589** [fredlcore/SolarEdge_Predictive_Charging#4]
Hi,

I've just come across this and interested in trying to modify it for my sunsynk inverter.

Are you able to give an example of the output format for `get_values(inverter)` please? I can then try and recreate that format with data from my inverter?

**Comment by fredlcore** [comment]
I _think_ it's a JSON structure that can then be accessed in python by addressing it as an array, like here:
```
batteryCapacity = (values['batteries']['Battery1']['rated_energy'])
```
However, I'm not a Python expert, and the programmer of the actual library that this function is taken from can tell you more about it, if necessary.
